baseURL = 'https://nsd-multi.yeojido.io/'
languageCode = 'ko-KR'
title = '낙성대 다국적노래방 엘론: ELON'

[params]
  isAdsEnabled = true
  adsTelegramId = "ggyuvely"

  description = '낙성대 다국적노래방 엘론은 관악구 신림동 1432-73에서 운영되는 다국적노래방 업소로, 낙성대·사당에서 여러 나라 노래를 즐기는 분들이 찾는다.'
  author = '두리'
  datePublished = "2026-08-18T09:16:00+09:00"
  dateModified = "2026-08-18T09:16:00+09:00"
  [params.store]
  tel = "010-8306-5747"
  location = "낙성대"
  locationEn = "NSD"
  name = "엘론"
  nameEn = "ELON"
  category = "다국적노래방"
  categoryEn = "Multi-KTV"
  address = "서울 관악구"
  googleMapSrc = "https://www.google.com/maps?q=서울+관악구&output=embed"
	[params.store.social.kakaoTalk]
	  id = ""
	  link = ""
	[params.store.social.telegram]
    id = ""
    link = ""

enableRobotsTXT = false
cleanDestinationDir = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
